website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)

    from .views import views

    app.register_blueprint(views, url_prefix='/') 

    return app

website/views.py
from flask import Blueprint, render_template

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html")

@views.route('/flashcards')
def flashcards():
    return render_template("flashcards.html")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
  <body>
    <main>
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

website/templates/flashcards.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 

{% block content %}
    <h1 style="margin-left: 20px;">My Flashcard!</h1>
    <p style="margin-left: 20px;">View your flashcards:</p>
    <a href="{{ url_for('views.home') }}" class="btn btn-primary" style="margin-left: 20px;">Return</a>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} 

{% block content %}
  <h1 style="margin-left: 20px;">Welcome to My Flashcard App!</h1>
  <p style="margin-left: 20px;">Click the button below to view your flashcards:</p>
  <a href="{{ url_for('views.flashcards') }}" class="btn btn-primary" style="margin-left: 20px;">View Flashcards</a>
{% endblock %}